"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";

type Data = {
  organization: { name: string; is_external: boolean };
  surface: string;
  window_days: number;
  by_channel: Record<string, number>;
  expires_at: number;
};

export default function ShareView() {
  const params = useParams<{ token: string }>();
  const [data, setData] = useState<Data | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!params?.token) return;
    fetch(`/api/v1/share/${params.token}`)
      .then(async (r) => {
        if (!r.ok) throw new Error(await r.text());
        return r.json();
      })
      .then(setData)
      .catch((e) => setError(e instanceof Error ? e.message : "Failed"));
  }, [params?.token]);

  if (error) {
    return (
      <main className="mx-auto max-w-2xl px-6 py-16">
        <h1 className="font-display text-2xl font-semibold mb-2">
          This share link can&apos;t be opened
        </h1>
        <p className="text-sm opacity-70">{error}</p>
      </main>
    );
  }
  if (!data) {
    return (
      <main className="mx-auto max-w-2xl px-6 py-16 text-sm opacity-60">
        Loading…
      </main>
    );
  }

  const total = Object.values(data.by_channel).reduce((a, b) => a + b, 0);

  return (
    <main className="mx-auto max-w-3xl px-6 py-12 flex flex-col gap-8">
      <header className="flex flex-col gap-1">
        <div className="text-xs uppercase tracking-wider text-[var(--dk-fg-3)]">
          Shared dashboard · read-only
        </div>
        <h1 className="font-display text-3xl font-semibold">
          {data.organization.name}
        </h1>
        <p className="text-sm opacity-70">
          Last {data.window_days} days · {total.toLocaleString()} touchpoints across {Object.keys(data.by_channel).length} channels
        </p>
      </header>

      <section className="grid gap-3 sm:grid-cols-2">
        {Object.entries(data.by_channel)
          .sort((a, b) => b[1] - a[1])
          .map(([channel, count]) => {
            const pct = total > 0 ? (count / total) * 100 : 0;
            return (
              <div
                key={channel}
                className="rounded-md border border-[var(--dk-border)] p-4 bg-white"
              >
                <div className="flex items-center justify-between mb-2">
                  <span className="font-medium capitalize">{channel}</span>
                  <span className="font-mono text-sm opacity-70">
                    {count.toLocaleString()}
                  </span>
                </div>
                <div className="h-1.5 rounded bg-[var(--dk-gray-100)] overflow-hidden">
                  <div
                    className="h-full bg-[var(--dk-purple-400)]"
                    style={{ width: `${pct.toFixed(1)}%` }}
                  />
                </div>
                <div className="text-xs opacity-60 mt-1">
                  {pct.toFixed(1)} % of touchpoints
                </div>
              </div>
            );
          })}
      </section>

      <footer className="text-xs opacity-50 text-center pt-4 border-t border-[var(--dk-border)]">
        Generated by DClaw Marketing · this link expires automatically
      </footer>
    </main>
  );
}
