"""Admin-only user management endpoints.

The platform does NOT support self-service signup. Admins create users
with a one-shot autogenerated temp password; the user is forced to
reset on first login.
"""

from typing import Annotated
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, status
from fastapi_users.password import PasswordHelper
from pydantic import BaseModel, EmailStr, Field
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.auth import current_superuser
from app.auth.manager import generate_temp_password
from app.auth.schemas import UserRead
from app.core.database import get_db
from app.models.user import User


router = APIRouter(prefix="/admin", tags=["admin"], dependencies=[Depends(current_superuser)])
_password_helper = PasswordHelper()


class AdminUserCreate(BaseModel):
    email: EmailStr
    full_name: str | None = None
    is_superuser: bool = False  # set true to create another Admin


class AdminUserCreateResponse(BaseModel):
    user: UserRead
    temp_password: str = Field(
        description="ONE-SHOT autogenerated password. Share with the user; "
        "they must change it on first login. NEVER stored in plain text."
    )


class AdminUserUpdate(BaseModel):
    full_name: str | None = None
    is_active: bool | None = None
    is_superuser: bool | None = None


class AdminUserResetPasswordResponse(BaseModel):
    user_id: UUID
    temp_password: str = Field(
        description="ONE-SHOT new autogenerated password. User must reset on next login."
    )


@router.post("/users", response_model=AdminUserCreateResponse, status_code=status.HTTP_201_CREATED)
async def admin_create_user(
    body: AdminUserCreate,
    session: AsyncSession = Depends(get_db),
) -> AdminUserCreateResponse:
    # uniqueness check
    existing = await session.execute(select(User).where(User.email == body.email))
    if existing.scalar_one_or_none() is not None:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail=f"User with email {body.email} already exists.",
        )

    temp_password = generate_temp_password()
    user = User(
        email=body.email,
        hashed_password=_password_helper.hash(temp_password),
        is_active=True,
        is_superuser=body.is_superuser,
        is_verified=True,  # admin-created = trusted; no email-verify roundtrip
        full_name=body.full_name,
        password_reset_required=True,
    )
    session.add(user)
    await session.flush()
    await session.commit()
    await session.refresh(user)

    return AdminUserCreateResponse(user=UserRead.model_validate(user), temp_password=temp_password)


@router.get("/users", response_model=list[UserRead])
async def admin_list_users(
    session: AsyncSession = Depends(get_db),
    limit: int = 50,
    offset: int = 0,
) -> list[User]:
    result = await session.execute(
        select(User).order_by(User.created_at.desc()).limit(limit).offset(offset)
    )
    return list(result.scalars().all())


@router.get("/users/{user_id}", response_model=UserRead)
async def admin_get_user(
    user_id: UUID, session: AsyncSession = Depends(get_db)
) -> User:
    user = await session.get(User, user_id)
    if user is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="User not found.")
    return user


@router.patch("/users/{user_id}", response_model=UserRead)
async def admin_update_user(
    user_id: UUID,
    body: AdminUserUpdate,
    session: AsyncSession = Depends(get_db),
) -> User:
    user = await session.get(User, user_id)
    if user is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="User not found.")
    for field, value in body.model_dump(exclude_unset=True).items():
        setattr(user, field, value)
    await session.flush()
    await session.commit()
    await session.refresh(user)
    return user


@router.post("/users/{user_id}/reset-password", response_model=AdminUserResetPasswordResponse)
async def admin_force_reset_password(
    user_id: UUID, session: AsyncSession = Depends(get_db)
) -> AdminUserResetPasswordResponse:
    """Generates a new temp password for a user. Forces them to reset on
    next login. Use this when a user forgets their password and email
    reset is unavailable, or to revoke and re-issue.
    """
    user = await session.get(User, user_id)
    if user is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="User not found.")

    temp_password = generate_temp_password()
    user.hashed_password = _password_helper.hash(temp_password)
    user.password_reset_required = True
    await session.flush()
    await session.commit()

    return AdminUserResetPasswordResponse(user_id=user.id, temp_password=temp_password)


@router.delete("/users/{user_id}", status_code=status.HTTP_204_NO_CONTENT)
async def admin_delete_user(
    user_id: UUID,
    actor: User = Depends(current_superuser),
    session: AsyncSession = Depends(get_db),
) -> None:
    """Hard-delete a user row. Two safety gates:

    1. An admin can't delete themselves (would lock them out).
    2. The bootstrap admin (email matching
       ``settings.bootstrap_admin_email``) can't be deleted — it's the
       recovery account.

    Foreign keys to ``users`` are mostly ``ondelete=SET NULL`` (audit,
    memberships, etc.) so the cascade is non-destructive to history.
    """
    from app.core.config import settings as _settings

    user = await session.get(User, user_id)
    if user is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="User not found.")
    if user.id == actor.id:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="Admins cannot delete their own account.",
        )
    if user.email == _settings.bootstrap_admin_email:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail=(
                "The bootstrap admin account is the recovery path and "
                "cannot be deleted."
            ),
        )
    await session.delete(user)
    await session.commit()
