"""Admin-only user management endpoints.

The platform does NOT support self-service signup. Admins create users
with a one-shot autogenerated temp password; the user is forced to
reset on first login.
"""

from typing import Annotated
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, status
from fastapi_users.password import PasswordHelper
from pydantic import BaseModel, EmailStr, Field
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.auth import current_superuser
from app.auth.manager import generate_temp_password
from app.auth.schemas import UserRead
from app.core.database import get_db
from app.models.user import User


router = APIRouter(prefix="/admin", tags=["admin"], dependencies=[Depends(current_superuser)])
_password_helper = PasswordHelper()


class AdminUserCreate(BaseModel):
    email: EmailStr
    full_name: str | None = None
    is_superuser: bool = False  # set true to create another Admin


class AdminUserCreateResponse(BaseModel):
    user: UserRead
    temp_password: str = Field(
        description="ONE-SHOT autogenerated password. Share with the user; "
        "they must change it on first login. NEVER stored in plain text."
    )


class AdminUserUpdate(BaseModel):
    full_name: str | None = None
    is_active: bool | None = None
    is_superuser: bool | None = None


class AdminUserResetPasswordResponse(BaseModel):
    user_id: UUID
    temp_password: str = Field(
        description="ONE-SHOT new autogenerated password. User must reset on next login."
    )


@router.post("/users", response_model=AdminUserCreateResponse, status_code=status.HTTP_201_CREATED)
async def admin_create_user(
    body: AdminUserCreate,
    session: AsyncSession = Depends(get_db),
) -> AdminUserCreateResponse:
    # uniqueness check
    existing = await session.execute(select(User).where(User.email == body.email))
    if existing.scalar_one_or_none() is not None:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail=f"User with email {body.email} already exists.",
        )

    from app.services.slugs import make_slug

    if body.is_superuser:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail=(
                "Only the bootstrap account can be a superadmin. Make this "
                "user an org admin via OrganizationMembership instead."
            ),
        )

    temp_password = generate_temp_password()
    user = User(
        email=body.email,
        hashed_password=_password_helper.hash(temp_password),
        is_active=True,
        is_superuser=False,
        is_verified=True,
        full_name=body.full_name,
        password_reset_required=True,
        slug=make_slug("u", body.full_name or body.email.split("@")[0]),
    )
    session.add(user)
    await session.flush()
    await session.commit()
    await session.refresh(user)

    return AdminUserCreateResponse(user=UserRead.model_validate(user), temp_password=temp_password)


class OrgAssignment(BaseModel):
    """One (org, role) assignment in the combined create call."""
    org_id: UUID
    role: str


class AdminUserWithOrgsCreate(BaseModel):
    email: EmailStr
    full_name: str | None = None
    orgs: list[OrgAssignment] = Field(default_factory=list)


class CreatedMembershipRead(BaseModel):
    id: UUID
    organization_id: UUID
    user_id: UUID
    role: str


class AdminUserWithOrgsResponse(BaseModel):
    user: UserRead
    temp_password: str
    memberships: list[CreatedMembershipRead] = Field(default_factory=list)


@router.post(
    "/users/with-org",
    response_model=AdminUserWithOrgsResponse,
    status_code=status.HTTP_201_CREATED,
)
async def admin_create_user_with_orgs(
    body: AdminUserWithOrgsCreate,
    actor: User = Depends(current_superuser),
    session: AsyncSession = Depends(get_db),
) -> AdminUserWithOrgsResponse:
    """Create a user and attach them to zero or more orgs in one transaction.

    The new-org flow is intentionally NOT in this endpoint — clients should
    call POST /orgs first (which is also transactional and auto-derives the
    slug), receive the new org_id, and pass it here as one of the
    `orgs[]` entries.
    """
    from app.models.organization import (
        Organization,
        OrganizationMembership,
        OrganizationRole,
    )
    from app.services.audit import write_audit_event
    from app.services.slugs import make_slug

    # Uniqueness check.
    if (
        await session.execute(select(User).where(User.email == body.email))
    ).scalar_one_or_none() is not None:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail=f"User with email {body.email} already exists.",
        )

    # Validate every (org_id, role) pair before any writes.
    for assn in body.orgs:
        try:
            OrganizationRole(assn.role)
        except ValueError:
            raise HTTPException(
                status_code=400, detail=f"Invalid role: {assn.role}"
            )
        target_org = await session.get(Organization, assn.org_id)
        if target_org is None:
            raise HTTPException(
                status_code=404,
                detail=f"Organization {assn.org_id} not found.",
            )

    # Create user.
    temp_password = generate_temp_password()
    user = User(
        email=body.email,
        hashed_password=_password_helper.hash(temp_password),
        is_active=True,
        is_superuser=False,
        is_verified=True,
        full_name=body.full_name,
        password_reset_required=True,
        slug=make_slug("u", body.full_name or body.email.split("@")[0]),
    )
    session.add(user)
    await session.flush()

    memberships: list[OrganizationMembership] = []
    for assn in body.orgs:
        role_enum = OrganizationRole(assn.role)
        m = OrganizationMembership(
            user_id=user.id,
            organization_id=assn.org_id,
            role=role_enum,
        )
        session.add(m)
        memberships.append(m)
        await write_audit_event(
            session,
            action_type="admin.user.create_with_org",
            organization_id=assn.org_id,
            actor_user_id=actor.id,
            target_type="user",
            target_id=user.id,
            payload={"role": assn.role},
        )

    await session.flush()
    await session.commit()
    await session.refresh(user)
    for m in memberships:
        await session.refresh(m)

    return AdminUserWithOrgsResponse(
        user=UserRead.model_validate(user),
        temp_password=temp_password,
        memberships=[
            CreatedMembershipRead(
                id=m.id,
                organization_id=m.organization_id,
                user_id=m.user_id,
                role=m.role.value,
            )
            for m in memberships
        ],
    )


@router.get("/users", response_model=list[UserRead])
async def admin_list_users(
    session: AsyncSession = Depends(get_db),
    limit: int = 50,
    offset: int = 0,
) -> list[User]:
    result = await session.execute(
        select(User).order_by(User.created_at.desc()).limit(limit).offset(offset)
    )
    return list(result.scalars().all())


@router.get("/users/{user_id}", response_model=UserRead)
async def admin_get_user(
    user_id: UUID, session: AsyncSession = Depends(get_db)
) -> User:
    user = await session.get(User, user_id)
    if user is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="User not found.")
    return user


@router.patch("/users/{user_id}", response_model=UserRead)
async def admin_update_user(
    user_id: UUID,
    body: AdminUserUpdate,
    actor: User = Depends(current_superuser),
    session: AsyncSession = Depends(get_db),
) -> User:
    user = await session.get(User, user_id)
    if user is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="User not found.")

    patch = body.model_dump(exclude_unset=True)

    # Self-demote guard — a superadmin cannot toggle off their own flag.
    if (
        actor.id == user.id
        and "is_superuser" in patch
        and patch["is_superuser"] is False
        and user.is_superuser
    ):
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="A superadmin cannot revoke their own superadmin flag.",
        )

    for field, value in patch.items():
        setattr(user, field, value)
    await session.flush()
    await session.commit()
    await session.refresh(user)
    return user


@router.post("/users/{user_id}/reset-password", response_model=AdminUserResetPasswordResponse)
async def admin_force_reset_password(
    user_id: UUID, session: AsyncSession = Depends(get_db)
) -> AdminUserResetPasswordResponse:
    """Generates a new temp password for a user. Forces them to reset on
    next login. Use this when a user forgets their password and email
    reset is unavailable, or to revoke and re-issue.
    """
    user = await session.get(User, user_id)
    if user is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="User not found.")

    temp_password = generate_temp_password()
    user.hashed_password = _password_helper.hash(temp_password)
    user.password_reset_required = True
    await session.flush()
    await session.commit()

    return AdminUserResetPasswordResponse(user_id=user.id, temp_password=temp_password)


class UserMembershipRead(BaseModel):
    org_id: UUID
    org_slug: str
    org_name: str
    role: str


@router.get("/users/{user_id}/memberships", response_model=list[UserMembershipRead])
async def admin_list_user_memberships(
    user_id: UUID,
    session: AsyncSession = Depends(get_db),
) -> list[UserMembershipRead]:
    """Returns every org the user is a member of, with role + org metadata.

    Used by the admin users page to show which orgs each user belongs to.
    """
    from app.models.organization import Organization, OrganizationMembership

    rows = (
        await session.execute(
            select(OrganizationMembership, Organization)
            .join(Organization, Organization.id == OrganizationMembership.organization_id)
            .where(OrganizationMembership.user_id == user_id)
        )
    ).all()
    return [
        UserMembershipRead(
            org_id=org.id,
            org_slug=org.slug,
            org_name=org.name,
            role=m.role.value,
        )
        for (m, org) in rows
    ]


@router.delete("/users/{user_id}", status_code=status.HTTP_204_NO_CONTENT)
async def admin_delete_user(
    user_id: UUID,
    actor: User = Depends(current_superuser),
    session: AsyncSession = Depends(get_db),
) -> None:
    """Hard-delete a user row. Two safety gates:

    1. An admin can't delete themselves (would lock them out).
    2. The bootstrap admin (email matching
       ``settings.bootstrap_admin_email``) can't be deleted — it's the
       recovery account.

    Foreign keys to ``users`` are mostly ``ondelete=SET NULL`` (audit,
    memberships, etc.) so the cascade is non-destructive to history.
    """
    from app.core.config import settings as _settings

    user = await session.get(User, user_id)
    if user is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="User not found.")
    if user.id == actor.id:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="Admins cannot delete their own account.",
        )
    if user.email == _settings.bootstrap_admin_email:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail=(
                "The bootstrap admin account is the recovery path and "
                "cannot be deleted."
            ),
        )
    await session.delete(user)
    await session.commit()
