"""UserManager — FastAPI-Users hook for password validation and lifecycle.

Notable hooks we override:
- on_after_register: sets password_reset_required=True so the user is
  forced to change the admin-supplied temp password on first login.
- validate_password: enforces minimum complexity for the user-chosen
  password during the first-login reset.

The manager is async; depends on the SQLAlchemy user database adapter.
"""

# Defer annotation evaluation — needed because validate_password's
# signature uses `User | "UserCreate"` and SQLAlchemy's
# DeclarativeAttributeIntercept metaclass on User doesn't support the
# runtime `|` operator with a forward string reference.
from __future__ import annotations

import secrets
import string
from typing import Optional
from uuid import UUID

from fastapi import Depends, Request
from fastapi_users import BaseUserManager, UUIDIDMixin, exceptions
from fastapi_users.password import PasswordHelper

from app.auth.db import get_user_db
from app.core.config import settings
from app.models.user import User


_password_helper = PasswordHelper()


def generate_temp_password(length: int = 16) -> str:
    """Generates a strong random temp password for admin-created users.

    Mix of uppercase + lowercase + digits + symbols. Always >= 12 chars.
    """
    alphabet = string.ascii_letters + string.digits + "!@#$%^&*"
    while True:
        candidate = "".join(secrets.choice(alphabet) for _ in range(length))
        # Guarantee at least one of each char class
        if (
            any(c.isupper() for c in candidate)
            and any(c.islower() for c in candidate)
            and any(c.isdigit() for c in candidate)
            and any(c in "!@#$%^&*" for c in candidate)
        ):
            return candidate


class UserManager(UUIDIDMixin, BaseUserManager[User, UUID]):
    reset_password_token_secret = settings.jwt_secret
    verification_token_secret = settings.jwt_secret

    async def validate_password(
        self,
        password: str,
        user: User | "UserCreate",  # noqa: F821
    ) -> None:
        """Password rules. Applied at create + reset.

        - >= 10 chars
        - Cannot equal user's email local-part
        """
        if len(password) < 10:
            raise exceptions.InvalidPasswordException(
                reason="Password must be at least 10 characters."
            )
        email = user.email if hasattr(user, "email") else ""
        if email and email.split("@")[0].lower() in password.lower():
            raise exceptions.InvalidPasswordException(
                reason="Password must not contain your email's local part."
            )

    async def on_after_register(
        self, user: User, request: Optional[Request] = None
    ) -> None:
        """Mark every newly created user as needing a password reset.

        Admin-created users come in via /admin/users with an
        autogenerated temp password; they MUST reset on first login.
        Direct self-signup isn't exposed publicly, so this is consistent.
        """
        # Already True by default on the model; re-affirm explicitly.
        await self.user_db.update(user, {"password_reset_required": True})

    async def on_after_reset_password(
        self, user: User, request: Optional[Request] = None
    ) -> None:
        """Clear the first-login reset flag once a user successfully
        changes their password via /me/password.
        """
        await self.user_db.update(user, {"password_reset_required": False})


async def get_user_manager(user_db=Depends(get_user_db)):
    yield UserManager(user_db)


__all__ = ["UserManager", "get_user_manager", "generate_temp_password"]
